-- Alinea [Ocupación] y [Descripción Ocupación] con CIUO88AC (MinSalud)
-- Fuente: SQL/1888/CODESYSTEM/CIUO88AC.json
-- Regenerar: node tools/genOcupacionCiou88acUpdate.js
-- Match por código normalizado a 4 dígitos (ej. 110 -> 0110)
-- Nota: no usar WHERE con <> en collation CI; IHCE valida display con mayúsculas exactas.

BEGIN TRANSACTION;

UPDATE o
SET
    o.[Ocupación] = v.[Display],
    o.[Descripción Ocupación] = v.[Display]
FROM [dbo].[Ocupación] AS o
INNER JOIN (
    VALUES
        (N'0110', N'Oficiales de las Fuerzas Militares'),
        (N'0120', N'Suboficiales de las Fuerzas Militares'),
        (N'0130', N'Soldados de las Fuerzas Militares'),
        (N'0210', N'Oficiales de la Policía Nacional'),
        (N'0220', N'Suboficiales de la Policía Nacional'),
        (N'0230', N'Agentes de la Policía Nacional'),
        (N'0240', N'Auxiliares de la Policía Nacional'),
        (N'1110', N'Miembros del Poder Ejecutivo y de los cuerpos legislativos'),
        (N'1121', N'Directores generales, de empresas o entidades de la administración pública'),
        (N'1122', N'Directores de regionales, sucursales, oficinas y afines de la administración pública'),
        (N'1130', N'Jefes de comunidades indígenas, etnias especiales y afines'),
        (N'1141', N'Dirigentes y administradores de partidos políticos'),
        (N'1142', N'Dirigentes y administradores de organizaciones de empleadores, de trabajadores y de otras de interés socioeconómico'),
        (N'1143', N'Dirigentes y administradores de organizaciones humanitarias y de otras organizaciones especializadas'),
        (N'1211', N'Directores y gerentes generales de empresas privadas'),
        (N'1212', N'Directores de regionales, sucursales, oficinas y afines de empresas privadas'),
        (N'1311', N'Directores de departamentos de producción y operaciones en agricultura, ganaderia, silvicultura, caza y pesca'),
        (N'1312', N'Directores de departamentos de producción y operaciones en industrias manufactureras y extractivas'),
        (N'1313', N'Directores de departamentos de producción y operaciones en construcción y obras públicas'),
        (N'1314', N'Directores de departamentos de producción y operaciones en comercio mayorista y minorista'),
        (N'1315', N'Directores de departamentos de producción y operaciones en restaurantes, hoteles y afines'),
        (N'1316', N'Directores de departamentos de producción y operaciones en transporte, almacenamiento y comunicaciones'),
        (N'1317', N'Directores de departamentos de producción y operaciones en empresas de intermediación financiera y servicios a empresas'),
        (N'1318', N'Directores de departamentos de producción y operaciones en servicios de salud, educación y recreación'),
        (N'1319', N'Directores de departamentos de producción y operaciones, no clasificados bajo otros epígrafes'),
        (N'1321', N'Directores de departamentos financieros y administrativos'),
        (N'1322', N'Directores de departamentos de personal y de relaciones laborales'),
        (N'1323', N'Directores de departamentos de ventas y comercialización'),
        (N'1324', N'Directores de departamentos de publicidad y de relaciones públicas'),
        (N'1325', N'Directores de departamentos de abastecimiento y distribución'),
        (N'1326', N'Directores de departamentos de servicios de informática'),
        (N'1327', N'Directores de departamentos de investigaciones y desarrollo'),
        (N'1329', N'Otros directores de departamentos públicos y privados, no clasificados bajo otros epígrafes'),
        (N'1411', N'Coordinadores y supervisores financieros y administrativos'),
        (N'1412', N'Coordinadores y supervisores de  ventas y comercialización'),
        (N'1413', N'Coordinadores y supervisores de publicidad, información, relaciones públicas y servicio al cliente'),
        (N'1414', N'Coordinadores y supervisores de  almacenamiento, abastecimiento y distribución'),
        (N'1415', N'Coordinadores y supervisores de informática,  investigación y desarrollo'),
        (N'1416', N'Coordinadores y supervisores de servicios sociales, educación y salud'),
        (N'1419', N'Otros coordinadores y supervisores en mandos medios de empresas adminiatrativos, comerciales y de servicios de empresas públicas y privadas, no clasificados bajo otros epígrafes'),
        (N'1421', N'Coordinadores y supervisores de producción y operaciones en aprovechamiento agrícola, pecuario y silvícola'),
        (N'1422', N'Coordinadores y supervisores de producción y operaciones en explotación procesamiento y transporte de minerales, petróleo y gas'),
        (N'1423', N'Coordinadores y supervisores de producción y operaciones en  procesamiento, fabricación y ensamble'),
        (N'1424', N'Coordinadores y supervisores de  producción y operaciones en construcción y obras públicas'),
        (N'1425', N'Coordinadores y supervisores de producción y operaciones en  instalación, mantenimiento y reparación mecánica, eléctrica y electrónica'),
        (N'1426', N'Coordinadores y supervisores de  producción y operaciones en restaurantes, hoteles hospitales y afines'),
        (N'1427', N'Coordinadores y supervisores de producción y operaciones  en transporte y comunicaciones'),
        (N'1428', N'Coordinadores y supervisores de producción y operaciones en cuidados personales, limpieza y servicios similares'),
        (N'1429', N'Coordinadores y supervisores  en mandos medios de producción y operaciones en empresas públicas y privadas, no clasificados bajo otros epígrafes'),
        (N'2111', N'Físicos y astrónomos'),
        (N'2112', N'Meteorólogos'),
        (N'2113', N'Químicos y afines'),
        (N'2114', N'Geólogos y geofísicos'),
        (N'2121', N'Matemáticos y actuarios'),
        (N'2122', N'Estadísticos'),
        (N'2130', N'Profesionales de la informática'),
        (N'2141', N'Arquitectos y urbanistas'),
        (N'2142', N'Ingenieros civiles, ingenieros de transporte y afines'),
        (N'2143', N'Ingenieros eléctricos, ingenieros electrónicos, de telecomunicaciones y afines'),
        (N'2144', N'Ingenieros mecánicos'),
        (N'2145', N'Ingenieros industriales y afines'),
        (N'2146', N'Ingenieros químicos y afines'),
        (N'2147', N'Ingenieros de minas, ingenieros metalúrgicos y afines'),
        (N'2148', N'Ingenieros catastrales, ingenieros geógrafos y afines'),
        (N'2149', N'Arquitectos, ingenieros y afines, no clasificados bajo otros epígrafes'),
        (N'2211', N'Biólogos, botánicos, zoólogos y afines'),
        (N'2212', N'Patólogos y afines'),
        (N'2213', N'Agrónomos y afines'),
        (N'2221', N'Médicos'),
        (N'2222', N'Odontólogos'),
        (N'2223', N'Médicos veterinarios y zootecnistas'),
        (N'2224', N'Optómetras'),
        (N'2225', N'Fonoaudiólogos, fisioterapeutas y afines'),
        (N'2226', N'Enfermeros(as) profesionales'),
        (N'2227', N'Nutricionistas y dietistas'),
        (N'2229', N'Médicos, profesionales en ciencias de la salud y afines, no clasificados bajo otros epígrafes'),
        (N'2311', N'Profesores de universidades y otros establecimientos de educación superior'),
        (N'2312', N'Profesores de educación secundaria'),
        (N'2313', N'Profesores de educación  primaria'),
        (N'2314', N'Profesores de educación preescolar'),
        (N'2320', N'Profesores e instructores de educación especial'),
        (N'2331', N'Especialistas en métodos pedagógicos y material didáctico'),
        (N'2332', N'Inspectores de la educación'),
        (N'2333', N'Consejeros educativos'),
        (N'2339', N'Otros profesionales de la educación, no clasificados bajo otros epígrafes'),
        (N'2411', N'Contadores'),
        (N'2412', N'Especialistas en políticas, servicios de personal y afines'),
        (N'2413', N'Analistas y agentes financieros'),
        (N'2419', N'Profesionales en organización, administración de empresas, análisis financiero y afines, no clasificados bajo otros epígrafes'),
        (N'2421', N'Abogados'),
        (N'2422', N'Jueces'),
        (N'2429', N'Profesionales del derecho, no clasificados bajo otros epígrafes'),
        (N'2431', N'Catalogadores de piezas de museos, archivos y afines'),
        (N'2432', N'Bibliotecarios, documentalistas y afines'),
        (N'2441', N'Economistas'),
        (N'2442', N'Sociólogos, antropólogos y afines'),
        (N'2443', N'Filósofos, historiadores y especialistas en ciencias políticas'),
        (N'2444', N'Filólogos, traductores e intérpretes'),
        (N'2445', N'Psicólogos'),
        (N'2446', N'Trabajadores sociales y afines'),
        (N'2449', N'Profesionales en ciencias económicas, sociales y humanas no clasificados bajo otros epígrafes'),
        (N'2451', N'Escritores, periodistas y afines'),
        (N'2452', N'Escultores, pintores y afines'),
        (N'2453', N'Compositores, músicos y cantantes'),
        (N'2454', N'Coreógrafos y bailarines'),
        (N'2455', N'Actores y directores de cine, radio, teatro, televisión y afines'),
        (N'2456', N'Publicistas y afines'),
        (N'2460', N'Sacerdotes y religiosos de distintas doctrinas'),
        (N'3111', N'Técnicos y postsecundarios no universitarios en ciencias físicas, químicas y afines'),
        (N'3112', N'Técnicos y postsecundarios no universitarios en ingeniería civil, arquitectura, agrimensores y afines'),
        (N'3113', N'Electrotécnicos'),
        (N'3114', N'Técnicos y postsecundarios no universitarios en electrónica y telecomunicaciones'),
        (N'3115', N'Técnicos y postsecundarios no universitarios en mecánica y construcción mecánica'),
        (N'3116', N'Técnicos y postsecundarios no universitarios en ingeniería  industrial y química industrial'),
        (N'3117', N'Técnicos y postsecundarios no universitarios en ingeniería de minas y metalurgia'),
        (N'3118', N'Delineantes y dibujantes técnicos'),
        (N'3119', N'Técnicos y postsecundarios no universitarios en ciencias físicas, químicas e ingenierías, no clasificados bajo otros epígrafes'),
        (N'3121', N'Analistas de sistemas informáticos'),
        (N'3122', N'Técnicos en programación informática'),
        (N'3123', N'Técnicos en control de equipos informáticos'),
        (N'3124', N'Técnicos en control de robots industriales'),
        (N'3131', N'Fotógrafos y operadores de equipos de grabación de imagen y sonido'),
        (N'3132', N'Operadores de equipos de radiodifusión, televisión y telecomunicaciones'),
        (N'3133', N'Operadores de aparatos de diagnóstico y tratamiento médicos'),
        (N'3139', N'Operadores de equipos ópticos y electrónicos, no clasificados bajo otros epígrafes'),
        (N'3141', N'Oficiales maquinistas'),
        (N'3142', N'Capitanes, oficiales de cubierta y prácticos'),
        (N'3143', N'Pilotos de aviación y afines'),
        (N'3144', N'Controladores de tráfico aéreo y marítimo'),
        (N'3145', N'Técnicos en seguridad aeronáutica'),
        (N'3151', N'Inspectores de edificios y de prevención e investigación de incendios'),
        (N'3152', N'Inspectores de seguridad y salud y control de calidad'),
        (N'3211', N'Técnicos en ciencias biológicas y afines'),
        (N'3212', N'Técnicos en agronomía, zootecnia y silvicultura'),
        (N'3221', N'Practicantes y asistentes médicos'),
        (N'3222', N'Higienistas y promotores de salud'),
        (N'3223', N'Técnicos en optometría y ópticos'),
        (N'3224', N'Técnicos e higienistas dentales'),
        (N'3225', N'Técnicos terapeutas, quiroprácticos y afines'),
        (N'3226', N'Técnicos y asistentes veterinarios'),
        (N'3227', N'Técnicos y asistentes en farmacia'),
        (N'3229', N'Técnicos, postsecundarios no universitarios y asistentes de la medicina moderna y la salud (excepto el personal de partería), no clasificados bajo otros epígrafes'),
        (N'3231', N'Practicantes de la medicina tradicional'),
        (N'3232', N'Curanderos'),
        (N'3233', N'Parteras'),
        (N'3311', N'Asistentes de enseñanza en educación  superior, secundaria y primaria'),
        (N'3312', N'Asistentes de enseñanza en educación preescolar'),
        (N'3320', N'Asistentes de educación especial'),
        (N'3331', N'Instructores de educación vocacional artística y técnica'),
        (N'3332', N'Instructores de educación vocacional artesanal'),
        (N'3333', N'Instructores medios de transporte y afines'),
        (N'3411', N'Agentes de seguros'),
        (N'3412', N'Agentes inmobiliarios'),
        (N'3413', N'Agentes de viajes'),
        (N'3414', N'Representantes comerciales y técnicos de ventas'),
        (N'3415', N'Compradores'),
        (N'3416', N'Tasadores y subastadores'),
        (N'3419', N'Técnicos, postsecundarios no universitarios y asistentes en operaciones comerciales, no clasificados bajo otros epígrafes'),
        (N'3421', N'Agentes de compras, intermediarios y consignatarios'),
        (N'3422', N'Asistentes de comercio exterior'),
        (N'3423', N'Agentes públicos y privados de colocación y contratistas de mano de obra'),
        (N'3429', N'Agentes comerciales y corredores, no clasificados bajo otros epígrafes'),
        (N'3431', N'Técnicos, postsecundarios no universitarios y asistentes de servicios administrativos y afines'),
        (N'3432', N'Técnicos, postsecundarios no universitarios y asistentes del derecho y servicios legales y afines'),
        (N'3433', N'Técnicos, postsecundarios no universitarios y asistentes de servicios financieros, contables y afines'),
        (N'3434', N'Técnicos, postsecundarios no universitarios y asistentes de servicios estadísticos, matemáticos y afines'),
        (N'3439', N'Técnicos, postsecundarios no universitarios y asistentes de servicios de administración, no clasificados bajo otros epígrafes'),
        (N'3441', N'Agentes de aduana e inspectores de fronteras'),
        (N'3442', N'Funcionarios del fisco'),
        (N'3443', N'Funcionarios de servicios de seguridad social'),
        (N'3444', N'Funcionarios de servicios de expedición de licencias y permisos'),
        (N'3449', N'Agentes de la administración pública en aduanas, impuestos y afines, no clasificados bajo otros epígrafes'),
        (N'3450', N'Inspectores de policía, detectives y afines'),
        (N'3460', N'Asistentes en trabajo social y comunitario'),
        (N'3471', N'Técnicos en diseño y decoradores'),
        (N'3472', N'Locutores de radio, televisión y afines'),
        (N'3473', N'Músicos, cantantes y bailarines callejeros, de cabaret y afines'),
        (N'3474', N'Recreadores, payasos, acróbatas, prestidigitadores y afines'),
        (N'3475', N'Atletas, deportistas y afines'),
        (N'3476', N'Asistentes de cine, teatro, televisión y artes escénicas'),
        (N'3480', N'Auxiliares laicos de los cultos'),
        (N'4111', N'Mecanógrafos, transcriptores de textos y afines'),
        (N'4112', N'Operadores de calculadoras y entrada de datos'),
        (N'4113', N'Secretarios(as)'),
        (N'4121', N'Auxiliares de contabilidad y cálculo de costos'),
        (N'4122', N'Auxiliares de servicios estadísticos y financieros'),
        (N'4123', N'Auxiliares administrativos y afines'),
        (N'4131', N'Encargados de control de abastecimientos e inventario'),
        (N'4132', N'Encargados de servicios de apoyo a la producción'),
        (N'4133', N'Encargados de servicios de transporte'),
        (N'4141', N'Empleados de bibliotecas y archivos'),
        (N'4142', N'Empleados de servicios de correo'),
        (N'4143', N'Codificadores de datos, correctores de pruebas de imprenta y afines'),
        (N'4144', N'Escribientes públicos y afines'),
        (N'4211', N'Cajeros y expendedores de billetes'),
        (N'4212', N'Taquilleros'),
        (N'4213', N'Receptores de apuestas y afines'),
        (N'4214', N'Prestamistas'),
        (N'4215', N'Cobradores y afines'),
        (N'4221', N'Empleados de servicios de líneas de viajes aéreas, marítimas y terrestres'),
        (N'4222', N'Recepcionistas, empleados de información y servicio al cliente'),
        (N'4223', N'Empleados telefonistas y de servicios de internet'),
        (N'5111', N'Personal de servicio a pasajeros'),
        (N'5112', N'Revisores, guardas y cobradores de los servicios de transporte'),
        (N'5113', N'Guías'),
        (N'5121', N'Cocineros y afines'),
        (N'5122', N'Meseros, taberneros y afines'),
        (N'5131', N'Niñeras y cuidadoras infantiles'),
        (N'5132', N'Auxiliares de enfermería y odontología'),
        (N'5139', N'Trabajadores de los cuidados personales y afines, no clasificados bajo otros epígrafes'),
        (N'5141', N'Peluqueros, especialistas en tratamientos de belleza y afines'),
        (N'5142', N'Acompañantes'),
        (N'5143', N'Personal de pompas fúnebres y embalsamadores'),
        (N'5149', N'Otros trabajadores de servicios personales a particulares, no clasificados bajo otros epígrafes'),
        (N'5150', N'Astrólogos, adivinadores, quirománticos y afines'),
        (N'5211', N'Bomberos y rescatistas'),
        (N'5212', N'Agentes y policías de transito'),
        (N'5213', N'Guardianes de prisión'),
        (N'5219', N'Personal de los servicios de protección y seguridad, no clasificado bajo otros epígrafes'),
        (N'5310', N'Modelos de modas, arte y publicidad'),
        (N'5320', N'Vendedores y demostradores de tiendas, almacenes y afines'),
        (N'5330', N'Vendedores en quioscos y puestos fijos de mercado'),
        (N'5341', N'Vendedores ambulantes'),
        (N'5342', N'Vendedores a domicilio y por teléfono'),
        (N'6111', N'Agricultores de cultivos transitorios'),
        (N'6112', N'Agricultores de cultivos permanentes (plantaciones de árboles y arbustos)'),
        (N'6113', N'Trabajadores de huertas, invernaderos, viveros y jardines'),
        (N'6114', N'Trabajadores forestales'),
        (N'6115', N'Trabajadores agropecuarios'),
        (N'6121', N'Criadores de ganado y trabajadores de la cría de animales domésticos diversos'),
        (N'6122', N'Avicultores'),
        (N'6123', N'Criadores de insectos, apicultores, sericicultores y afines'),
        (N'6129', N'Trabajadores pecuarios, avicultores, criadores de insectos y afines, no clasificados bajo otros epígrafes'),
        (N'6131', N'Criadores de especies acuáticas'),
        (N'6132', N'Pescadores'),
        (N'6133', N'Cazadores y tramperos'),
        (N'6211', N'Obreros y peones agropecuarios de labranza y de invernadero'),
        (N'6212', N'Obreros forestales'),
        (N'6213', N'Obreros de pesca, caza y trampa'),
        (N'7111', N'Mineros y canteros'),
        (N'7112', N'Pegadores cargas explosivas'),
        (N'7113', N'Tronzadores, labrantes y grabadores de piedra'),
        (N'7211', N'Albañiles, mamposteros y afines'),
        (N'7212', N'Operarios en cemento armado, enfoscadores y afines'),
        (N'7213', N'Carpinteros de armar y de blanco'),
        (N'7219', N'Oficiales y operarios de la construcción en obra negra y afines, no clasificados bajo otros epígrafes'),
        (N'7221', N'Techadores'),
        (N'7222', N'Parqueteros y colocadores de suelos'),
        (N'7223', N'Instaladores de material aislante y de insonorización'),
        (N'7224', N'Cristaleros'),
        (N'7225', N'Fontaneros e instaladores de tuberías'),
        (N'7226', N'Electricistas de obras y afines'),
        (N'7231', N'Revocadores'),
        (N'7232', N'Pintores, empapeladores y afines'),
        (N'7233', N'Limpiadores de fachadas y deshollinadores'),
        (N'7311', N'Moldeadores y macheros'),
        (N'7312', N'Soldadores y oxicortadores'),
        (N'7313', N'Chapistas y caldereros'),
        (N'7314', N'Montadores de estructuras metálicas'),
        (N'7315', N'Aparejadores y empalmadores de cables'),
        (N'7316', N'Pintores,  barnizadores y enlacadores de artículos metálicos y afines'),
        (N'7321', N'Herreros y forjadores'),
        (N'7322', N'Herramentistas y afines'),
        (N'7323', N'Pulidores de metales y afiladores de herramientas'),
        (N'7411', N'Mecánicos y ajustadores de vehículos de motor'),
        (N'7412', N'Mecánicos y ajustadores de motores de avión'),
        (N'7413', N'Mecánicos y ajustadores de máquinas agrícolas e industriales'),
        (N'7414', N'Mecánicos y ajustadores de máquinas herramientas'),
        (N'7421', N'Mecánicos y ajustadores eléctricos'),
        (N'7422', N'Mecánicos, reparadores y ajustadores de aparatos electrónicos'),
        (N'7423', N'Instaladores y reparadores de telégrafos, teléfonos y líneas electricas'),
        (N'7511', N'Mecánicos y reparadores de instrumentos de precisión'),
        (N'7512', N'Fabricantes y afinadores de instrumentos musicales'),
        (N'7521', N'Cajistas, tipógrafos y afines'),
        (N'7522', N'Estereotipistas y galvanotipistas'),
        (N'7523', N'Grabadores de imprenta y fotograbadores'),
        (N'7524', N'Operarios de la fotografía y afines'),
        (N'7525', N'Encuadernadores y afines'),
        (N'7526', N'Impresores de sericigrafía y estampadores a la plancha y en textiles'),
        (N'7611', N'Alfareros y afines (barro, arcilla y abrasivos)'),
        (N'7612', N'Sopladores, modeladores, laminadores, cortadores y pulidores de vidrio'),
        (N'7613', N'Grabadores de vidrio'),
        (N'7614', N'Pintores decoradores de vidrio, cerámica y otros materiales'),
        (N'7621', N'Cesteros, bruceros y afines'),
        (N'7622', N'Artesanos de la madera y materiales similares'),
        (N'7631', N'Artesanos de los tejidos, el cuero y materiales similares'),
        (N'7632', N'Bordadores y afines'),
        (N'7641', N'Joyeros, orfebres y plateros'),
        (N'7642', N'Floristas y arreglistas florales'),
        (N'7649', N'Otros artesanos, no clasificados bajo otros epígrafes'),
        (N'7711', N'Carniceros, pescaderos y afines'),
        (N'7712', N'Panaderos, pasteleros y confiteros'),
        (N'7713', N'Operarios de la elaboración de productos lácteos'),
        (N'7714', N'Operarios de la conservación de frutas, legumbres, verduras y afines'),
        (N'7715', N'Catadores y clasificadores de alimentos y bebidas'),
        (N'7716', N'Preparadores y elaboradores de tabaco y sus productos'),
        (N'7721', N'Preparadores de fibras'),
        (N'7722', N'Tejedores con telares o de tejidos de punto y afines'),
        (N'7723', N'Sastres, modistos costureros, sombrereros y afines'),
        (N'7724', N'Peleteros y afines'),
        (N'7725', N'Tapiceros, colchoneros y afines'),
        (N'7731', N'Apelambradores, pellejeros y curtidores'),
        (N'7732', N'Zapateros y afines'),
        (N'7741', N'Operarios del tratamiento de la madera'),
        (N'7742', N'Ebanistas y afines'),
        (N'7743', N'Ajustadores y operadores de máquinas de labrar madera'),
        (N'8111', N'Operadores de instalaciones mineras'),
        (N'8112', N'Operadores de instalaciones de procesamiento de minerales y rocas'),
        (N'8113', N'Perforadores y sondistas de pozos y afines'),
        (N'8121', N'Operadores de hornos de minerales y de hornos de primera fusión de metales'),
        (N'8122', N'Operadores de hornos de segunda fusión, máquinas de colar y moldear metales y trenes de laminación'),
        (N'8123', N'Operadores de instalaciones de tratamiento térmico de metales'),
        (N'8124', N'Operadores de máquinas trefiladoras y estiradoras de metales'),
        (N'8131', N'Operadores de mezcladoras, de hornos de vidriería  y máquinas afines'),
        (N'8132', N'Operadores de mezcladoras, de  hornos de cerámica y máqinas afines'),
        (N'8139', N'Operadores de instalaciones de vidriería, cerámica y afines, no clasificados bajo otros epígrafes'),
        (N'8141', N'Operadores de instalaciones de procesamiento de la madera'),
        (N'8142', N'Operadores de instalaciones para la preparación de pasta o pulpa de papel'),
        (N'8143', N'Operadores de instalaciones para la fabricación de papel'),
        (N'8151', N'Operadores de instalaciones quebrantadoras, trituradoras y mezcladoras de sustancias químicas'),
        (N'8152', N'Operadores de instalaciones de tratamiento químico térmico'),
        (N'8153', N'Operadores de equipos de filtración y separación de sustancias químicas'),
        (N'8154', N'Operadores de equipos de destilación y de reacción química (excepto petróleo y gas natural)'),
        (N'8155', N'Operadores de instalaciones de refinación de petróleo y gas natural'),
        (N'8159', N'Operadores de instalaciones de tratamientos químicos, no clasificados bajo otros epígrafes'),
        (N'8161', N'Operadores de instalaciones de producción de energía'),
        (N'8162', N'Operadores de máquinas de vapor y calderas'),
        (N'8163', N'Operadores de incineradores'),
        (N'8164', N'Operadores de instalaciones de tratamiento de agua y afines'),
        (N'8165', N'Operadores de instalaciones de refrigeración, calefacción y ventilación'),
        (N'8170', N'Operadores de cadenas de montaje automatizadas e instalaciones mecánicas y de robots industriales'),
        (N'8211', N'Operadores de máquinas herramientas y afines'),
        (N'8212', N'Operadores de máquinas para fabricar productos de cemento y otros productos minerales'),
        (N'8221', N'Operadores de máquinas para fabricar productos farmacéuticos y cosméticos'),
        (N'8222', N'Operadores de máquinas para fabricar municiones y explosivos'),
        (N'8223', N'Operadores de máquinas pulidoras, galvanizadoras y recubridoras de metales'),
        (N'8229', N'Operadores de máquinas para fabricar productos químicos, no clasificados bajo otros epígrafes'),
        (N'8231', N'Operadores de máquinas para fabricar productos de caucho'),
        (N'8232', N'Operadores de máquinas para fabricar productos de plástico'),
        (N'8240', N'Operadores de máquinas para fabricar productos de madera'),
        (N'8251', N'Operadores de máquinas de imprenta, reproducción fotográfica y afines'),
        (N'8252', N'Operadores de máquinas de encuadernación'),
        (N'8253', N'Operadores de máquinas para fabricar productos de papel y afines'),
        (N'8261', N'Operadores de máquinas de preparación de fibras, hilado y devanado'),
        (N'8262', N'Operadores de telares y otras máquinas tejedoras'),
        (N'8263', N'Operadores de máquinas para coser'),
        (N'8264', N'Operadores de máquinas de blanqueo, teñido y tintura'),
        (N'8265', N'Operadores de máquinas de tratamiento de pieles y cueros'),
        (N'8266', N'Operadores de máquinas para la fabricación de calzado y afines'),
        (N'8267', N'Patronistas, cortadores de tela, cuero y afines'),
        (N'8269', N'Operadores de máquinas para fabricar productos textiles y artículos de piel y cuero, no clasificados bajo otros epígrafes'),
        (N'8271', N'Operadores de máquinas para procesar carne, pescado y mariscos'),
        (N'8272', N'Operadores de máquinas para elaborar productos lácteos'),
        (N'8273', N'Operadores de máquinas para moler cereales y especias'),
        (N'8274', N'Operadores de máquinas para procesar cereales, productos de panadería, repostería y confitería'),
        (N'8275', N'Operadores de máquinas para procesar frutos húmedos, secos y hortalizas'),
        (N'8276', N'Operadores de máquinas para fabricar azúcares'),
        (N'8277', N'Operadores de máquinas para elaborar té, café y cacao'),
        (N'8278', N'Operadores de máquinas para elaborar cerveza, vinos y otras bebidas'),
        (N'8279', N'Operadores de máquinas para elaborar productos del tabaco'),
        (N'8281', N'Ensambladores de mecanismos y elementos mecánicos de máquinas'),
        (N'8282', N'Ensambladores de equipos eléctricos'),
        (N'8283', N'Ensambladores de equipos electrónicos'),
        (N'8284', N'Ensambladores de productos metálicos, de caucho y plástico'),
        (N'8285', N'Ensambladores de productos de madera y materiales afines'),
        (N'8286', N'Ensambladores de productos de cartón, textiles y materiales afines'),
        (N'8290', N'Otros operadores de máquinas y ensambladores'),
        (N'8311', N'Maquinistas de vehículos por riel'),
        (N'8312', N'Guardafrenos, guardagujas y agentes de maniobras'),
        (N'8321', N'Conductores de camionetas y vehículos livianos'),
        (N'8322', N'Conductores de taxis'),
        (N'8323', N'Conductores de buses, microbuses y colectivos'),
        (N'8324', N'Conductores de camiones y vehículos pesados'),
        (N'8331', N'Operadores de maquinaria agrícola y forestal motorizada'),
        (N'8332', N'Operadores de máquinas de movimiento de tierras, construcción vías y afines'),
        (N'8333', N'Operadores de grúas, de aparatos elevadores y afines'),
        (N'8334', N'Operadores de carretillas elevadoras'),
        (N'8340', N'Marineros de cubierta y afines'),
        (N'9111', N'Ayudante de taller, mecánica, vehículos de motor y afines'),
        (N'9112', N'Ayudantes en reparación y mecánica en general (excepto vehículos de motor)'),
        (N'9120', N'Limpiabotas y otros trabajadores callejeros'),
        (N'9131', N'Mensajeros, porteadores y repartidores'),
        (N'9132', N'Porteros , conserjes y afines'),
        (N'9133', N'Vigilantes y celadores'),
        (N'9134', N'Recolectores y surtidores de aparatos automáticos'),
        (N'9135', N'Lectores de medidores'),
        (N'9141', N'Recolectores de basura'),
        (N'9142', N'Barrenderos y afines'),
        (N'9143', N'Recolectores de material reciclable'),
        (N'9210', N'Personal doméstico'),
        (N'9221', N'Aseadores y fumigadores de oficinas, hoteles y otros establecimientos'),
        (N'9222', N'Lavanderos y planchadores manuales'),
        (N'9223', N'Lavadores de vehículos, ventanas y afines'),
        (N'9311', N'Obreros de minas y canteras'),
        (N'9312', N'Obreros de obras públicas y mantenimiento: carreteras, presas y obras similares'),
        (N'9313', N'Obreros de la construcción de edificios'),
        (N'9321', N'Obreros de ensamble'),
        (N'9322', N'Embaladores manuales y otros obreros de la industria manufacturera'),
        (N'9331', N'Conductores de vehículos accionados a pedal o a brazo'),
        (N'9332', N'Conductores de vehículos de tracción animal'),
        (N'9333', N'Obreros de carga')
) AS v([Codigo], [Display])
    ON RIGHT(
        REPLICATE(N'0', 4) + LTRIM(RTRIM(CAST(o.[Código Ocupación] AS NVARCHAR(20)))),
        4
    ) = v.[Codigo];

SELECT @@ROWCOUNT AS RegistrosActualizados;

-- Verificación rápida (código 0110)
SELECT [Id Ocupación], [Código Ocupación], [Ocupación], [Descripción Ocupación]
FROM [dbo].[Ocupación]
WHERE RIGHT(REPLICATE(N'0', 4) + LTRIM(RTRIM([Código Ocupación])), 4) = N'0110';

COMMIT TRANSACTION;
-- ROLLBACK TRANSACTION;
