-- INSERT generado desde ISO31661.json
-- Grupo usado: ISO31661N - Numeric Codes
-- Fuente de verdad: CodeSystem ISO31661
-- Total países: 249

INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('004', N'Afghanistan', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('008', N'Albania', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('010', N'Antarctica', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('012', N'Algeria', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('016', N'American Samoa', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('020', N'Andorra', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('024', N'Angola', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('028', N'Antigua and Barbuda', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('031', N'Azerbaijan', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('032', N'Argentina', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('036', N'Australia', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('040', N'Austria', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('044', N'Bahamas', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('048', N'Bahrain', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('050', N'Bangladesh', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('051', N'Armenia', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('052', N'Barbados', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('056', N'Belgium', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('060', N'Bermuda', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('064', N'Bhutan', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('068', N'Bolivia, Plurinational State of', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('070', N'Bosnia and Herzegovina', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('072', N'Botswana', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('074', N'Bouvet Island', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('076', N'Brazil', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('084', N'Belize', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('086', N'British Indian Ocean Territory', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('090', N'Solomon Islands', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('092', N'Virgin Islands, British', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('096', N'Brunei Darussalam', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('100', N'Bulgaria', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('104', N'Myanmar', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('108', N'Burundi', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('112', N'Belarus', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('116', N'Cambodia', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('120', N'Cameroon', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('124', N'Canada', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('132', N'Cabo Verde', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('136', N'Cayman Islands', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('140', N'Central African Republic', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('144', N'Sri Lanka', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('148', N'Chad', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('152', N'Chile', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('156', N'China', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('158', N'Taiwan, Province of China', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('162', N'Christmas Island', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('166', N'Cocos (Keeling) Islands', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('170', N'Colombia', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('174', N'Comoros', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('175', N'Mayotte', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('178', N'Congo', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('180', N'Congo, the Democratic Republic of the', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('184', N'Cook Islands', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('188', N'Costa Rica', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('191', N'Croatia', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('192', N'Cuba', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('196', N'Cyprus', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('203', N'Czechia', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('204', N'Benin', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('208', N'Denmark', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('212', N'Dominica', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('214', N'Dominican Republic', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('218', N'Ecuador', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('222', N'El Salvador', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('226', N'Equatorial Guinea', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('231', N'Ethiopia', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('232', N'Eritrea', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('233', N'Estonia', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('234', N'Faroe Islands', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('238', N'Falkland Islands (Malvinas)', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('239', N'South Georgia and the South Sandwich Islands', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('242', N'Fiji', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('246', N'Finland', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('248', N'Åland Islands', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('250', N'France', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('254', N'French Guiana', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('258', N'French Polynesia', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('260', N'French Southern Territories', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('262', N'Djibouti', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('266', N'Gabon', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('268', N'Georgia', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('270', N'Gambia', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('275', N'Palestine, State of', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('276', N'Germany', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('288', N'Ghana', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('292', N'Gibraltar', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('296', N'Kiribati', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('300', N'Greece', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('304', N'Greenland', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('308', N'Grenada', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('312', N'Guadeloupe', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('316', N'Guam', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('320', N'Guatemala', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('324', N'Guinea', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('328', N'Guyana', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('332', N'Haiti', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('334', N'Heard Island and McDonald Islands', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('336', N'Holy See', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('340', N'Honduras', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('344', N'Hong Kong', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('348', N'Hungary', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('352', N'Iceland', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('356', N'India', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('360', N'Indonesia', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('364', N'Iran, Islamic Republic of', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('368', N'Iraq', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('372', N'Ireland', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('376', N'Israel', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('380', N'Italy', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('384', N'Côte d''Ivoire', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('388', N'Jamaica', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('392', N'Japan', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('398', N'Kazakhstan', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('400', N'Jordan', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('404', N'Kenya', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('408', N'Korea, Democratic People''s Republic of', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('410', N'Korea, Republic of', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('414', N'Kuwait', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('417', N'Kyrgyzstan', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('418', N'Lao People''s Democratic Republic', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('422', N'Lebanon', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('426', N'Lesotho', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('428', N'Latvia', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('430', N'Liberia', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('434', N'Libya', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('438', N'Liechtenstein', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('440', N'Lithuania', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('442', N'Luxembourg', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('446', N'Macao', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('450', N'Madagascar', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('454', N'Malawi', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('458', N'Malaysia', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('462', N'Maldives', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('466', N'Mali', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('470', N'Malta', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('474', N'Martinique', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('478', N'Mauritania', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('480', N'Mauritius', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('484', N'Mexico', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('492', N'Monaco', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('496', N'Mongolia', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('498', N'Moldova, Republic of', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('499', N'Montenegro', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('500', N'Montserrat', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('504', N'Morocco', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('508', N'Mozambique', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('512', N'Oman', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('516', N'Namibia', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('520', N'Nauru', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('524', N'Nepal', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('528', N'Netherlands', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('531', N'Curaçao', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('533', N'Aruba', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('534', N'Sint Maarten (Dutch part)', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('535', N'Bonaire, Sint Eustatius and Saba', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('540', N'New Caledonia', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('548', N'Vanuatu', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('554', N'New Zealand', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('558', N'Nicaragua', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('562', N'Niger', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('566', N'Nigeria', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('570', N'Niue', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('574', N'Norfolk Island', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('578', N'Norway', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('580', N'Northern Mariana Islands', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('581', N'United States Minor Outlying Islands', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('583', N'Micronesia, Federated States of', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('584', N'Marshall Islands', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('585', N'Palau', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('586', N'Pakistan', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('591', N'Panama', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('598', N'Papua New Guinea', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('600', N'Paraguay', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('604', N'Peru', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('608', N'Philippines', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('612', N'Pitcairn', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('616', N'Poland', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('620', N'Portugal', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('624', N'Guinea-Bissau', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('626', N'Timor-Leste', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('630', N'Puerto Rico', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('634', N'Qatar', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('638', N'Réunion', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('642', N'Romania', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('643', N'Russian Federation', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('646', N'Rwanda', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('652', N'Saint Barthélemy', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('654', N'Saint Helena, Ascension and Tristan da Cunha', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('659', N'Saint Kitts and Nevis', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('660', N'Anguilla', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('662', N'Saint Lucia', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('663', N'Saint Martin (French part)', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('666', N'Saint Pierre and Miquelon', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('670', N'Saint Vincent and the Grenadines', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('674', N'San Marino', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('678', N'Sao Tome and Principe', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('682', N'Saudi Arabia', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('686', N'Senegal', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('688', N'Serbia', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('690', N'Seychelles', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('694', N'Sierra Leone', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('702', N'Singapore', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('703', N'Slovakia', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('704', N'Viet Nam', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('705', N'Slovenia', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('706', N'Somalia', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('710', N'South Africa', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('716', N'Zimbabwe', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('724', N'Spain', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('728', N'South Sudan', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('729', N'Sudan', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('732', N'Western Sahara', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('740', N'Suriname', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('744', N'Svalbard and Jan Mayen', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('748', N'Swaziland', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('752', N'Sweden', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('756', N'Switzerland', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('760', N'Syrian Arab Republic', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('762', N'Tajikistan', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('764', N'Thailand', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('768', N'Togo', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('772', N'Tokelau', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('776', N'Tonga', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('780', N'Trinidad and Tobago', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('784', N'United Arab Emirates', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('788', N'Tunisia', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('792', N'Turkey', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('795', N'Turkmenistan', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('796', N'Turks and Caicos Islands', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('798', N'Tuvalu', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('800', N'Uganda', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('804', N'Ukraine', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('807', N'Macedonia, the former Yugoslav Republic of', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('818', N'Egypt', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('826', N'United Kingdom', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('831', N'Guernsey', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('832', N'Jersey', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('833', N'Isle of Man', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('834', N'Tanzania, United Republic of', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('840', N'United States of America', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('850', N'Virgin Islands, U.S.', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('854', N'Burkina Faso', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('858', N'Uruguay', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('860', N'Uzbekistan', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('862', N'Venezuela, Bolivarian Republic of', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('876', N'Wallis and Futuna', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('882', N'Samoa', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('887', N'Yemen', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('894', N'Zambia', 7);
