--OJO CADA QUE SE REALICE UN CAMBIO DE RESOLUCION CUANDO ES UN CLIENTE FENALCO SE DEBE DILIGENCIAR ESTE CAMPO EL CUAL ENCONTRARAS AL INGRESAR A FENALCO 
--https://factible.fenalcoantioquia.com/FactibleWebService/interfaces/inicio.jsp
--CON LAS CREDENCIALES DEL PROYECTO
ALTER TABLE [EmpresaV]
ADD idnumeracionFenalco INT NULL;