INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('004', N'AFGANISTÁN', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('008', N'ALBANIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('010', N'ANTÁRTIDA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('012', N'ARGELIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('016', N'SAMOA AMERICANA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('020', N'ANDORRA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('024', N'ANGOLA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('028', N'ANTIGUA Y BARBUDA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('031', N'AZERBAIYÁN', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('032', N'ARGENTINA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('036', N'AUSTRALIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('040', N'AUSTRIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('044', N'BAHAMAS', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('048', N'BARÉIN', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('050', N'BANGLADÉS', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('051', N'ARMENIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('052', N'BARBADOS', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('056', N'BÉLGICA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('060', N'BERMUDA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('064', N'BUTÁN', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('068', N'BOLIVIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('070', N'BOSNIA-HERZEGOVINA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('072', N'BOTSUANA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('074', N'ISLA BOUVET', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('076', N'BRAZIL', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('084', N'BELICE', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('086', N'TERRITORIO BRITÁNICO DEL OCÉANO ÍNDICO', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('090', N'ISLAS SOLOMON', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('092', N'ISLAS VÍRGENES BRITÁNICAS', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('096', N'BRUNÉI', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('100', N'BULGARIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('104', N'MYANMAR (FORMER BURMA)', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('108', N'BURUNDI', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('112', N'BIELORRUSIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('116', N'CAMBOYA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('120', N'CAMERÚN', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('124', N'CANADÁ', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('132', N'CABO VERDE', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('136', N'ISLAS CAIMÁN', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('140', N'REPÚBLICA CENTROAFRICANA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('144', N'SRI LANKA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('148', N'CHAD', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('152', N'CHILE', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('156', N'CHINA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('158', N'TAIWAN', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('162', N'ISLA DE NAVIDAD', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('166', N'ISLAS COCOS', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('170', N'COLOMBIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('174', N'COMORAS', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('175', N'MAYOTTE', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('178', N'CONGO', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('180', N'REPÚBLICA DEMOCRÁTICA DEL CONGO', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('184', N'ISLAS COOK', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('188', N'COSTA RICA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('191', N'CROACIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('192', N'CUBA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('196', N'CHIPRE', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('203', N'REPÚBLICA CHECA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('204', N'BENIN', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('208', N'DINAMARCA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('212', N'DOMINICA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('214', N'REPÚBLICA DOMINICANA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('218', N'ECUADOR', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('222', N'EL SALVADOR', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('226', N'GUINEA ECUATORIAL', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('231', N'ETIOPIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('232', N'ERITREA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('233', N'ESTONIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('234', N'ISLAS FEROE', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('238', N'ISLAS MALVINAS', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('239', N'ISLAS GEORGIAS DEL SUR Y SANDWICH DEL SUR', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('242', N'FIYI', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('246', N'FINLANDIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('248', N'ALAND', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('250', N'FRANCIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('254', N'GUAYANA FRANCESA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('258', N'POLINESIA FRANCESA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('260', N'TIERRAS AUSTRALES Y ANTÁRTICAS FRANCESAS', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('262', N'YIBUTI', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('266', N'GABON', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('268', N'GEORGIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('270', N'GAMBIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('275', N'PALESTINA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('276', N'ALEMANIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('288', N'GHANA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('292', N'GIBRALTAR', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('296', N'KIRIBATI', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('300', N'GRECIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('304', N'GROENLANDIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('308', N'GRANADA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('312', N'GUADALUOE', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('316', N'GUAM', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('320', N'GUATEMALA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('324', N'GUINEA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('328', N'GUYANA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('332', N'HAITI', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('334', N'ISLA HEARD Y MCDONALD', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('336', N'SANTA SEDE', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('340', N'HONDURAS', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('344', N'HONG KONG', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('348', N'HUNGRÍA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('352', N'ISLANDIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('356', N'INDIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('360', N'INDONESIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('364', N'IRÁN', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('368', N'IRAQ', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('372', N'IRLANDA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('376', N'ISRAEL', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('380', N'ITALIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('384', N'COSTA DE MARFIL', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('388', N'JAMAICA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('392', N'JAPÓN', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('398', N'KAZAJISTÁN', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('400', N'JORDANIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('404', N'KENYA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('408', N'COREA DEL NORTE', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('410', N'COREA DEL SUR', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('414', N'KUWAIT', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('417', N'KIRGUISTÁN', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('418', N'LAOS', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('422', N'LÍBANO', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('426', N'LESOTO', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('428', N'LETONIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('430', N'LIBERIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('434', N'LIBIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('438', N'LIECHTENSTEIN', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('440', N'LITUANIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('442', N'LUXEMBURGO', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('446', N'MACAO', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('450', N'MADAGASCAR', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('454', N'MALAUI', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('458', N'MALASIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('462', N'MALDIVAS', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('466', N'MALI', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('470', N'MALTA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('474', N'MARTINICA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('478', N'MAURITANIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('480', N'MAURICIO', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('484', N'MÉXICO', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('492', N'MÓNACO', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('496', N'MONGOLIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('498', N'MOLDAVIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('499', N'MONTENEGRO', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('500', N'MONTSERRAT', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('504', N'MARRUECOS', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('508', N'MOZAMBIQUE', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('512', N'OMÁN', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('516', N'NAMIBIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('520', N'NAURU', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('524', N'NEPAL', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('528', N'PAÍSES BAJOS', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('531', N'CURAZAO', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('533', N'ARUBA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('534', N'SAN MARTÍN (parte holandesa)', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('535', N'BONAIRE, SAN EUSTAQUIO Y SABA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('540', N'NUEVA CALEDONIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('548', N'VANUATU', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('554', N'NUEVA ZELANDA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('558', N'NICARAGUA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('562', N'NIGER', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('566', N'NIGERIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('570', N'NIUE', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('574', N'ISLA NORFOLK', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('578', N'NORUEGA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('580', N'ISLAS MARIANAS DEL NORTE', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('581', N'ISLAS ULTRAMARINAS MENORES DE ESTADOS UNIDOS', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('583', N'MICRONESIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('584', N'ISLAS MARSHALL', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('585', N'PALAOS', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('586', N'PAQUISTAN', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('591', N'PANAMÁ', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('598', N'PAPUA NUEVA GUINEA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('600', N'PARAGUAY', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('604', N'PERÚ', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('608', N'FILIPINAS', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('612', N'PITCAIRN', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('616', N'POLONIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('620', N'PORTUGAL', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('624', N'GUINEA-BISÁU', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('626', N'TIMOR ORIENTAL', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('630', N'PUERTO RICO', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('634', N'CATAR', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('638', N'REUNION', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('642', N'RUMANIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('643', N'RUSIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('646', N'RUANDA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('652', N'SAN BARTOLOMÉ', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('654', N'SANTA HELENA, ASCENSIÓN Y TRISTÁN DE ACUÑA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('659', N'SAN CRISTÓBAL Y NIEVES', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('660', N'ANGUILA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('662', N'SANTA LUCIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('663', N'SAN MARTÍN (parte francesa)', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('666', N'SAN PEDRO Y MIQUELON', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('670', N'SAN VICENTE Y LAS GRANADINAS', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('674', N'SAN MARINO', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('678', N'SANTO TOME Y PRINCIPE', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('682', N'ARABIA SAUDITA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('686', N'SENEGAL', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('688', N'SERBIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('690', N'SEYCHELLES', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('694', N'SIERRA LEONA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('702', N'SINGAPUR', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('703', N'ESLOVAQUIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('704', N'VIETNAM', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('705', N'ESLOVENIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('706', N'SOMALIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('710', N'SUDÁFRICA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('716', N'ZIMBABUE', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('724', N'ESPAÑA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('728', N'SUDÁN DEL SUR', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('729', N'SUDÁN', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('732', N'SAHARA OCCIDENTAL', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('740', N'SURINAM', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('744', N'SVALBARD Y JAN MAYEN', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('748', N'SUAZILANDIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('752', N'SUECIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('756', N'SUIZA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('760', N'SIRIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('762', N'TAYIKISTÁN', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('764', N'TAILANDIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('768', N'TOGO', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('772', N'TOKELAU', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('776', N'TONGA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('780', N'TRINIDAD Y TOBAGO', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('784', N'EMIRATOS ÁRABES UNIDOS', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('788', N'TÚNEZ', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('792', N'TURQUÍA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('795', N'TURKMENISTAN', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('796', N'ISLAS TURCAS Y CAICOS', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('798', N'TUVALU', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('800', N'UGANDA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('804', N'UCRANIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('807', N'MACEDONIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('818', N'EGIPTO', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('826', N'REINO UNIDO', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('831', N'GUERNSEY', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('832', N'JERSEY', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('833', N'ISLA DE MAN', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('834', N'TANZANIA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('840', N'ESTADOS UNIDOS', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('850', N'ISLAS VÍRGENES DE LOS ESTADOS UNIDOS', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('854', N'BURKINA FASO', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('858', N'URUGUAY', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('860', N'UZBEKISTAN', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('862', N'VENEZUELA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('876', N'WALLIS Y FUTUNA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('882', N'SAMOA', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('887', N'YEMEN', 7);
INSERT INTO dbo.[País1888] (Codigo, Nombre, Estado) VALUES ('894', N'ZAMBIA', 7);